### ISSUE TITLE
reactions.fn.collectSeries sets strange return argument

### ISSUE THREAD

**Issue by outbounder** [vbogdanov/reactions#1]
When invoked done arguments are similar to:

```
false [ undefined, undefined, undefined, undefined, '-1': undefined ]
```

notice the '-1' argument.

using reactions.fn.collectParallel returns the array properly without '-1'. 

That was spotted on array of 5 functions, but it is hard to get the source code sample out of the other stuff arount it atm... :)

**Comment by vbogdanov** [comment]
fixed in version 0.0.9
